# Use the official TensorFlow image from Docker Hub
FROM tensorflow/tensorflow:2.7.0

# Install dependencies
RUN pip install --no-cache-dir streamlit tensorflow numpy pandas scikit-learn

# Set the working directory in the container
WORKDIR /app

# Copy all files into the working directory in the container
COPY . /app

# Expose port 8501 for Streamlit
EXPOSE 8501

# Command to run Streamlit when the container starts
CMD ["streamlit", "run", "app.py"]
